@startuml
    class Calculator {
        + hello(): string
        + create_mysql_connection(): void
        + addition(): int
        + subtraction(): int
        + multiplication(): int
        + division(): int
    }
@enduml
